Unit tests
Gituser143/cryptgo pull request #28
Opened 2021-10-02 17:42 UTC by nolancon

Some more basic unit tests to help out with #6

2021-10-02 17:58 UTC, Gituser143 requested changes

2021-10-02 17:58 UTC, Gituser143 commented on pkg/display/allcoin/allCoin_test.go
> +			},
@nolancon maybe add a few cases where filter happens using the name of the coin? As of now the `filterRows()` function checks if the given filter string exists in either the symbol name or the name itself.

2021-10-03 08:31 UTC, Gituser143 approved these changes
This looks great! Unless you'd like to add more tests, I'll merge this PR.

2021-10-03 09:58 UTC, nolancon commented
Cool. You can merge this as is, thanks.

2021-10-03 15:27 UTC, merged

2021-10-03 15:27 UTC, Gituser143 commented
@nolancon thank you for your contribution!