Add makefile and update CI to use make targets
Gituser143/cryptgo pull request #29
Opened 2021-10-02 18:23 UTC by nolancon

2021-10-03 08:24 UTC, Gituser143 commented
This is a great idea! Although I'm not very sure of how the modified GitHub workflows would work. I'll test around a bit before merging this.

2021-10-03 09:09 UTC, Gituser143 commented
@nolancon could you please add "make" subsection in the readme for building? Apart from that everything looks perfect!

2021-10-07 08:26 UTC, Gituser143 requested changes

2021-10-07 08:26 UTC, Gituser143 commented on Makefile
> +	docker run -u $(id -u):$(id -g) -v "$(HOME):/home/appuser/" --rm -it bhargavsnv/cryptgo:$(VERSION)
Could this be extended to take arguments too? `cryptgo portfolio` or `cryptgo --help` and such commands cannot be run using this currently.

2021-10-07 08:26 UTC, Gituser143 commented on Makefile
> +
This is absolutely brilliant! Tedious, but I ❤️ it nonetheless :P

2021-10-07 08:26 UTC, Gituser143 commented on Makefile
> +	docker build -t cryptgo .
This is on me, but could this be changed to `bhargavsnv/cryptgo` instead of just `cryptgo`?

2021-10-07 18:32 UTC, Gituser143 requested changes

2021-10-07 18:32 UTC, Gituser143 commented on Makefile
> +	go build -v ./...
@nolancon could you replace this with `go build cryptgo.go` as this creates and places a binary while `go build -v ./...` does not.

2021-10-07 18:32 UTC, Gituser143 commented
Also, could you please avoid force pushing? Multiple commits are fine, I'll be squashing them before merge anyway.

2021-10-08 07:04 UTC, Gituser143 approved these changes
Everything looks good! If there's nothing else you had in mind to add, I'll merge this?

2021-10-08 07:40 UTC, nolancon commented
> Everything looks good! If there's nothing else you had in mind to add, I'll merge this?

Nothing else. You can go ahead and merge 👍

2021-10-08 08:09 UTC, merged

2021-10-08 08:09 UTC, Gituser143 commented
@nolancon Thank you for your contribution!